server:
  port: 8080

spring:
  application:
    name: mi-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/PetVeterinariaDB
    username: postgres
    password: jose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: asapsitterapp@gmail.com
      password: ureeixyewmaiumra
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            ssl:
              trust: smtp.gmail.com
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB

minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio1234
  bucket-name: aaasdfv